### ISSUE TITLE
Could not find a valid gem 'cocoapods-framework' 

### ISSUE THREAD

**Issue by LeeCenY** [TyrantDante/cocoapods-xcframework#1]
` gem install cocoapods-framework`

ERROR:  Could not find a valid gem 'cocoapods-framework' (>= 0) in any repository
ERROR:  Possible alternatives: cocoapods-Framework

**Comment by LeeCenY** [comment]
It works, but I don't know how to use it 
`$ pod framework NAME [SOURCE]`

**Comment by TyrantDante** [comment]
#3  i change the name to cocoapods-xcframework. it support as `gem install cocoapods-xcframework`
