### ISSUE TITLE
包含子库的私有库 头文件 找不到

### ISSUE THREAD

**Issue by xyhuangjia** [TyrantDante/cocoapods-xcframework#14]
例如
```s.source_files = 'ZZChainKit/Classes/ZZChainKit.h'```
`ZZChainKit.h'` 在打出来的framework中是找不到的

**Comment by TyrantDante** [comment]
有定义在public_header 中么？

**Comment by xyhuangjia** [comment]
都有的

> 2021年6月24日 下午8:00，TyrantDante ***@***.***> 写道：
> 
> public_header

**Comment by xyhuangjia** [comment]
> 有定义在public_header 中么？
设置过
 s.public_header_files = 'ZAChainKit/Classes/ZAChainKit.h'
