### ISSUE TITLE
pod framework XXX.podspec --spec-sources=http://xxx/PubSpecs.git,https://github.com/CocoaPods/Specs.git --verbose

### ISSUE THREAD

**Issue by l1Dan** [TyrantDante/cocoapods-xcframework#17]
-> Pod installation complete! There are 27 dependencies from the Podfile and 23 total pods installed.
Building framework XXX (1.4.0.480) with configuration Release
Work dir is :/var/folders/02/vv9z58b97hqdw5nytjh2jc2w0000gn/T/frameworks-ssnk9wrx/Pods
--- Building framework XXX (1.4.0.480) with general device
--- Building framework XXX (1.4.0.480) with simulator device
<<-EOF
        Build command failed: xcodebuild -create-xcframework -output /var/folders/02/vv9z58b97hqdw5nytjh2jc2w0000gn/T/frameworks-ssnk9wrx/Pods/XXX.xcframework 2>&1
        Output:
            error: at least one framework or library must be specified.

                  EOF

**Comment by TyrantDante** [comment]
看起来没有simulator的产物
