### ISSUE TITLE
Universal framework里缺少了armv7架构

### ISSUE THREAD

**Issue by buptwsg** [TyrantDante/cocoapods-xcframework#21]
你好，
　　Generic iOS Device里面包含的有armv7，为啥Universal framework里面却不包含呢？

**Comment by TyrantDante** [comment]
你的库是不是支持的ios11以上如果是的话 那就是不支持的

**Comment by FoneG** [comment]
不是很理解这句话，现在的库一般都是支持iOS11吧？但我的APP还需要支持32位的机子，打包的时候需要带上armv7，请问该这么操作呢

**Comment by FoneG** [comment]
> 你的库是不是支持的ios11以上如果是的话 那就是不支持的

不是很理解这句话，现在的库一般都是支持iOS11吧？但我的APP还需要支持32位的机子，打包的时候需要带上armv7，请问该这么操作呢

**Comment by TyrantDante** [comment]
意思是如果只支持ios11以上就没有armv7
