### ISSUE TITLE
gem install cocoapods-framework 报错

### ISSUE THREAD

**Issue by abu0306** [TyrantDante/cocoapods-xcframework#3]
~ gem install cocoapods-framework
ERROR:  Could not find a valid gem 'cocoapods-framework' (>= 0) in any repository
ERROR:  Possible alternatives: cocoapods-Framework

**Comment by TyrantDante** [comment]
title已经被注册了，你可以用 仓库中 pkg文件夹下的gem ，
```
gem install pkg/xxxx.gem  
```
来安装

**Comment by TyrantDante** [comment]
发布了 名字改成 cocoapods-xcframework
