### ISSUE TITLE
本地gem编译插件成功,安装之后gem list也显示该插件,但是pod plugins installed找不到插件

### ISSUE THREAD

**Issue by ProMonkeyZ** [TyrantDante/cocoapods-xcframework#33]
我的cocoapods是通过gem安装的
版本1.11.0
![image](https://user-images.githubusercontent.com/19204117/191555378-aeb20c3c-e73d-46a5-a91c-9570d1a7267a.png)
![image](https://user-images.githubusercontent.com/19204117/191555455-e0eff428-5056-4c5c-9fb6-1200dd4b6ed7.png)

**Comment by TyrantDante** [comment]
bundle 管理看下

gemfile里加上
gem cocoapods-xcframework

bundle install
bundle exe pod plugins installed
