### ISSUE TITLE
怎么把依赖的库一起打进去。

### ISSUE THREAD

**Issue by 451222664** [TyrantDante/cocoapods-xcframework#37]
同标题，谢谢

**Comment by TyrantDante** [comment]
现在貌似不支持这个功能

**Comment by TyrantDante** [comment]
https://github.com/TyrantDante/cocoapods-xcframework/issues/36 same

**Comment by yirankege** [comment]
是不是podspec里面包含s.dependency 'OpenSSL-Universal', '~> 1.1.1'这种都不可以依赖？会报错

Unable to find a specification for `OpenSSL-Universal (~> 1.1.1)` depended upon by `EMTradeInternal`
