### ISSUE TITLE
我尝试了多种操作，都不行，看不懂

### ISSUE THREAD

**Issue by LeeCenY** [TyrantDante/cocoapods-xcframework#5]
是否有这个类似功能
https://github.com/leavez/cocoapods-binary

**Comment by TyrantDante** [comment]
可以贴下你的报错信息不

**Comment by LeeCenY** [comment]
你先说说，如何使用吧！看看是不是我使用方法有问题

**Comment by TyrantDante** [comment]
pod framework xxx.podspec  --spec-sources={repo_source}  --force --configuration={Release/Debug}

**Comment by TyrantDante** [comment]
用最新的吧  最新的 是 0.0.5 已经丢到rubygem 如果还是不行，私聊下wx

**Comment by LeeCenY** [comment]
命令
`
pod framework TTTapticHelper.podspec --spec-sources=https://github.com/LeeCenY/TTSpecs.git --force --configuration=Release
`


![image](https://user-images.githubusercontent.com/9047094/112972784-3623ef00-9183-11eb-9931-5a84089582b5.png)

**Comment by TyrantDante** [comment]
看起来像是路径的问题，你先把你的路径改一下吧，我晚点时候兼容一下  
![Uploading image.png…]()

**Comment by TyrantDante** [comment]
![image](https://user-images.githubusercontent.com/9446796/113080933-534fd080-920a-11eb-9a73-014cc57d8f57.png)

**Comment by LeeCenY** [comment]
谢谢了，可以了

1、模拟器生成产生_CodeSignature目录 https://github.com/CocoaPods/Rome/issues/91
2、未来是否提供一个架构合并功能呢(armv7 arm64 x86_64 i386 )? 
3、未来是否考虑提供类似CocoaPods plugin：https://github.com/leavez/cocoapods-binary 与 https://github.com/CocoaPods/Rome

**Comment by TyrantDante** [comment]
架构合并应该不会提供了，因为我们已经使用了xcode的新特性 xcframework，我认为这个应该比架构合并更加优雅。
签名的问题我会关注一下，
第三个我不太明白你这边需要的功能是什么

**Comment by TyrantDante** [comment]
近期打算支持的功能:
- 提供静态库的源码调试功能

**Comment by LeeCenY** [comment]
@TyrantDante  第三点就是：在项目中的Podfile文件的第三方库或私有库，命令 pod install 即可生成对应的 framework(也可以指定哪个需要生成 framework)

**Comment by LeeCenY** [comment]
> 架构合并应该不会提供了，因为我们已经使用了xcode的新特性 xcframework，我认为这个应该比架构合并更加优雅。
> 签名的问题我会关注一下，
> 第三个我不太明白你这边需要的功能是什么

xcframework 方面我还需要去学习了解一下

**Comment by LeeCenY** [comment]
> 近期打算支持的功能:
> 
> * 提供静态库的源码调试功能

我提出的第三个里面也是有这个功能

**Comment by TyrantDante** [comment]
> @TyrantDante 第三点就是：在项目中的Podfile文件的第三方库或私有库，命令 pod install 即可生成对应的 framework(也可以指定哪个需要生成 framework)

这个功能我得想一想，目前我们一般都会有二进制的repo来做这个统一的二进制化，所以不是特别需要这个功能，不过我觉得这个想法是很好的
