### ISSUE TITLE
依赖管理

### ISSUE THREAD

**Issue by windtersharp** [TyrantDante/cocoapods-xcframework#8]
Cocoapods package 打包静态库会把依赖的开源库和私有仓库代码打进去，开源库和私有库能区分依赖吗？不想把开源库打进去
Cocooods-xcframework 这个插件如何配置参数,能支持吗

**Comment by TyrantDante** [comment]
现在没有把开源库打进去，而且不是很期望把开源库打进去，因为我觉得一个库就应该只有当前这个库里面的代码

**Comment by windtersharp** [comment]
你说的开源库包含私有构建的仓库吗？

**Comment by TyrantDante** [comment]
所有的，

**Comment by TyrantDante** [comment]
issue 先关了 如果还有问题可以再开
